# ----
# Site

title: YVFTs | The yEAh Network
url: "https://yvfts.ynwk.org"
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Invest in yEAh Very-Fungible Tokens (YVFTs). Browse the collection or invest in some yourself!
author:
  name:
  email:
  twitter: # twitter username without the @ symbol

# -----
# Build

timezone: Etc/UTC

permalink: pretty

paginate: 12
paginate_path: "page:num"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /items/1.png
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true